//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministradorOrtopediaVelásquez
{
    using System;
    using System.Collections.Generic;
    
    public partial class consulta
    {
        public consulta()
        {
            this.detalle_consulta = new HashSet<detalle_consulta>();
        }
    
        public int id { get; set; }
        public string codigo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public int idCliente { get; set; }
        public string descripcion { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual ICollection<detalle_consulta> detalle_consulta { get; set; }
    }
}
