//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministradorOrtopediaVelásquez
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_consulta
    {
        public Nullable<int> idProtesis { get; set; }
        public Nullable<int> idOrtesis { get; set; }
        public int idMedico { get; set; }
        public Nullable<int> idConsulta { get; set; }
    
        public virtual consulta consulta { get; set; }
        public virtual ortesis ortesis { get; set; }
        public virtual protesis protesis { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
