//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministradorOrtopediaVelásquez
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.consulta = new HashSet<consulta>();
        }
    
        public int id { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string email { get; set; }
        public string codigoUsuario { get; set; }
        public Nullable<int> tipoUsuario { get; set; }
        public string contrasenya { get; set; }
        public string sexo { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public string alergias { get; set; }
        public string especialidad { get; set; }
        public string experiencia { get; set; }
    
        public virtual ICollection<consulta> consulta { get; set; }
        public virtual TipoUsuario TipoUsuario1 { get; set; }
        public virtual detalle_consulta detalle_consulta { get; set; }
    }
}
